version: "3"
services:
  deconz:
    image: marthoc/deconz
    container_name: deconz
    restart: unless-stopped
    network_mode: host
    volumes:
      - config:/root/.local/share/dresden-elektronik/deCONZ
    devices:
      - /dev/ttyAMA0
    environment:
      - TZ=America/Detroit
      - DECONZ_VNC_MODE=1
      - DECONZ_VNC_PASSWORD="${VNC_PASSWORD}"
      - DECONZ_WEB_PORT=80
      - DECONZ_WS_PORT=443
      - DEBUG_INFO=1
      - DEBUG_APS=0
      - DEBUG_ZCL=0
      - DEBUG_ZDP=0
      - DEBUG_OTAU=0
volumes:
  config:
